name: Statistics
version: 0.0.1
author: Hypex
main: plugin.Statistics
depend: []
commands:
   statistics:
      description: Commands related to the plugin core
      usage: Syntax error! Perhaps you meant /<command> reload?
      aliases: [stat, st, stata]
permissions:
   statistics.*:
      description: Access to all plugin commands
      default: false
      children:
         statistics.admin: true
   statistics.admin:
      description: Administrator access (all commands)
      default: false
